name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version that matches your project's requirements

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: false  # Change this to `true` if you want to push the image in this step
        tags: myusername/myreactapp:latest  # Replace with your Docker Hub repo and tag

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true  # Change this to `false` if you only want to build the image
        tags: myusername/myreactapp:latest  # Replace with your Docker Hub repo and tag
